github_username: "michaelb"
home:
  tab_name: "HOME"
  file_location: "index.html"
  title: "Hi"
  welcome: ""
  bottom_left_message: "Yep, that's the bottom of the page"
  bottom_author_name: "Michael Bleuez"
  avatar: "assets/avatar.jpg"

  lead_card:
    title: "ABOUT ME"
    links_to: "gg"
    bold_message: "I'm a man of few words, but (too?) many ideas"
    message: "- \"A software engineer who has 15 years of experience in a domain that exists since five\" - Stephen Hawking, June 2009

      - \"42\" - Deep Thought, roughly 10M years before today

      - \"Hopefully the skills are better than the sense of humour\" - Plato, 400.BC "
    read_time: ""
    avatar: "assets/avatar.jpg"
    author_name: "Michael Bleuez"
    cover: "assets/perso_cover.jpg"

  cards:
    resume:
      message: "Available in French, English, web and PDF versions"
      bold_message: "My updated resume"
      avatar: "assets/blank.jpg"
      author_name: "Michael Bleuez"
      cover: "assets/cv.png"
      read_time: ""
      links_to: "https://michaelb.github.io/cv"
      size: "1/3"
    gallery:
      message: "These photos are free to copy, modify and display under fair use"
      bold_message: "Some photos of me or taken by me"
      author_name: "Michael Bleuez"
      cover : "assets/gallery_cover.jpg"
      links_to: "gallery.html"
      avatar: "assets/blank.jpg"
      read_time: ""
      size : "2/3"



projects:
  tab_name: "PROJECTS"
  file_location: "projects.html"
  title: "My projects"
  bottom_left_message: "Yep, that's the bottom of the page"
  welcome: ""
  lead_card:
    title: "SNIPRUN"
    links_to: "https://github.com/michaelb/sniprun"
    bold_message: "Run code directly from the editor"
    message: "
      Sniprun is a Neovim plugin that allows the user to select and run code directly from the editor. It supports a large amount of different languages (including compiled ones) and output display options, and is probably the best solution out there, surpassing easily even other editor's similar plugins (VSCode's Code Runner, Emacs' OrgMode code evaluation).



      This Rust + Lua work is my flagship open-source project, runs since August 2020 and has attracted many users and contributors."
    read_time: ""
    avatar: "assets/avatar.jpg"
    author_name: "Michael Bleuez"
    cover: "assets/Sniprun_social_preview.png"
    repo: True
    reponame: "michaelb/sniprun"
  cards_from_repo:
    sniprun:
      name: "michaelb/michaelb.github.io"
      message: "Homemade personnal website"
      size: "1/3"
      cover : "assets/website.jpg"
    dailythough:
      name: "michaelb/dailythough"
      message: "Saving my mood and what inspires me on each day"
      size: "1/3"
      cover: "assets/thought.jpg"
    vimtips:
      name: "michaelb/vim-tips"
      message: ""
      size: "1/3"
      cover: "assets/tips.png"
    libfprintinsec:
      name: "michaelb/libfprint-elan0c63-insecure"
      message: ""
      size: "2/3"
      cover: "assets/fp.jpg"
    donothing:
      name: "michaelb/do-nothing.vim"
      message: ""
      size: "1/3"
      cover: "assets/noothing.jpg"
    shogai:
      name: "michaelb/shogai"
      message: ""
      size: "1/2"
      cover: "assets/shogai.jpg"
    
    shogui:
      name: "michaelb/shogui"
      message: ""
      size: "1/2"
      cover: "assets/shogui.png"
    autoytdl:
      name: "michaelb/auto-ytdl"
      message: ""
      size: "1/3"
      cover: "assets/ayt.jpg"
    gopasscrack:
      name: "michaelb/go-passwd-crack"
      message: ""
      size: "1/3"
      cover: "assets/pas.jpg"
    clusterisation:
      name: "michaelb/point-clustering"
      size: "1/3"
      message: ""
      cover : ""


