github_username: "michaelb"
webpage_name: "Michael Bleuez | Software Engineer"
home:
  tab_name: "HOME"
  file_location: "index.html"
  title: "Hi, I'm Michael"
  welcome: "How do you do?"
  bottom_author_name: "Michael Bleuez"
  avatar: "assets/avatar.jpg"

  lead_card:
    title: "ABOUT ME"
    links_to: "about_me.html"
    bold_message: "A man of few words, but (too?) many ideas"
    message: "I'm a junior software engineer who likes challenge and automation. But beyond that?\nHere you go"
    read_time: ""
    avatar: "assets/avatar.jpg"
    author_name: "Michael Bleuez"
    cover: "assets/perso_cover.jpg"

  cards:
    resume:
      message: "Available in French, English, web and PDF versions"
      bold_message: "My updated resume"
      avatar: "assets/blank.jpg"
      author_name: "Michael Bleuez"
      cover: "assets/cv.png"
      read_time: ""
      links_to: "https://michaelb.github.io/cv"
      size: "1/3"
    gallery:
      message: "These photos are free to copy, modify and display under fair use"
      bold_message: "Some photos of me or taken by me"
      author_name: "michael bleuez"
      cover : "assets/gallery_cover.jpg"
      links_to: "gallery.html"
      avatar: "assets/blank.jpg"
      read_time: ""
      size : "2/3"
    I like..: 
      message: ""
      bold_message: "The awesome curiosities I've stumbled upon along my journey"
      author_name: ""
      cover : "assets/hobbies.gif"
      avatar: "assets/blank.jpg"
      read_time: ""
      links_to: "liked.html"
      size : "2/3"




projects:
  tab_name: "PROJECTS"
  file_location: "projects.html"
  title: "My projects"
  welcome: "Automatically updated from GitHub"
  lead_card:
    title: "SNIPRUN"
    links_to: "https://github.com/michaelb/sniprun"
    bold_message: "Run code directly from the editor"
    message: "
      Sniprun is a Neovim plugin that allows the user to select and run code directly from the editor. It supports a large amount of different languages (including compiled ones) and output display options, and is probably the best solution out there, surpassing easily even other editor's similar plugins (VSCode's Code Runner, Emacs' OrgMode code evaluation).



      This Rust + Lua work is my flagship open-source project, runs since August 2020 and has attracted many users and contributors."
    read_time: ""
    avatar: "assets/avatarmulti.jpg"
    author_name: "Michael Bleuez"
    cover: "assets/Sniprun_social_preview.png"
    repo: True
    reponame: "michaelb/sniprun"
  cards_from_repo:
    libfprintinsec:
      name: "michaelb/libfprint-elan0c63-insecure"
      message: "Who knew fingerprint readers could be so complicated yet so simple"
      size: "2/3"
      cover: "assets/fp.png"
    donothing:
      name: "michaelb/do-nothing.vim"
      message: ""
      size: "1/3"
      cover: "assets/noothing.jpg"
      avatar: "assets/avatarmulti.jpg"
    shogai:
      name: "michaelb/shogai"
      message: ""
      size: "1/2"
      cover: "assets/shogai.jpg"
    
    shogui:
      name: "michaelb/shogui"
      message: ""
      size: "1/2"
      cover: "assets/shogui.png"
    autoytdl:
      name: "michaelb/auto-ytdl"
      message: ""
      size: "1/3"
      cover: "assets/ayt.jpg"
      avatar: "assets/avatarmulti.jpg"
    gopasscrack:
      name: "michaelb/go-passwd-crack"
      message: ""
      size: "1/3"
      cover: "assets/pas.jpg"
    clusterisation:
      name: "michaelb/point-clustering"
      size: "1/3"
      message: ""
      cover : "assets/cluster.png"
    site:
      name: "michaelb/michaelb.github.io"
      message: "Homemade personnal website"
      size: "1/3"
      cover : "assets/website.jpg"
    dailythough:
      name: "michaelb/dailythough"
      message: "Saving my mood and what inspires me on each day"
      size: "1/3"
      cover: "assets/thought.jpg"
  cards:
    decac:
      message: "(This repository is private)"
      bold_message: "Compiler for an object-oriented programming language"
      avatar: "assets/avatarmulti.jpg"
      author_name: "Michael Bleuez and 4 teammates"
      avatarlink: ""
      cover: "assets/decac.png"
      read_time: "Java"
      links_to: ""
      size: "1/3"


liked:
  ignore_in_nav: ""
  file_location: "liked.html"
  title: "What I like"
  welcome: "Awesome curiosities"
  cards:
    cursed iceberg:
      message: "From weird to chaotic-evil computer quirks"
      bold_message: "The cursed computer iceberg meme"
      avatar: "assets/suricrasia.png"
      avatarlink: "https://suricrasia.online/"
      author_name: "suricrasia"
      cover: "assets/iceberg.png"
      read_time: ""
      links_to: "https://suricrasia.online/iceberg/"
      size: "1/3"

    art of code:
      bold_message: "Art of code talk @NDC2020"
      message: ""
      avatar: "assets/ndc.jpg"
      avatarlink: "https://dylanbeattie.net/"
      author_name: "Dylan Beattie"
      read_time: ""
      links_to: "https://www.youtube.com/watch?v=6avJHaC3C2U"
      size: "1/3"
      cover: "assets/artofcode.png"

    neovim:
      bold_message: "An hyper-extensible, cutting edge Vim-based text editor"
      links_to: "https://neovim.io/"
      avatar: "assets/blank.jpg"
      read_time: ""
      size: "1/3"
      cover: "assets/neovim-mark.png"
      message: ""
      author_name: ""

    uroboros quine:
      links_to: "https://github.com/mame/quine-relay"
      bold_message: "A mind-blowing quine"
      read_time: ""
      author_name: "Yusuke Endoh"
      message: ""
      size: "1/3"
      cover: "assets/langs.png"
      avatar: "assets/mame.png"
      avatarlink: "https://github.com/mame"

    landauer's principle:
      bold_message: "Information == energy"
      message: "Between thermodynamics, CS and quantics lies a mindblowing little demon"
      links_to: "https://en.wikipedia.org/wiki/Landauer%27s_principle"
      size : "1/3"
      author_name: ""
      avatar: "assets/blank.jpg"
      read_time: ""
      cover: "assets/land.png"

    ingenuity:
      bold_message: "a small copter at the very bleeding edge of spatial exploration for both hardware and software"
      links_to: "https://github.com/readme/featured/nasa-ingenuity-helicopter"
      size: "1/3"
      author_name: "Klint Finley"
      read_time: "Read time: 8min"
      message: ""
      cover: "assets/ing.jpg"
      avatar: "assets/finley.png"
      avatarlink: "https://klintfinley.com/"

    cmake raytracer:
      bold_message: "Why CMake is ridiculously complex"
      message: ""
      size: "1/3"
      cover: "assets/rt.png"
      avatar: "assets/64.png"
      avatarlink: "https://github/64"
      read_time: ""
      author_name: "64"
      links_to: "https://github.com/64/cmake-raytracer"

contact:
  tab_name: "CONTACT ME"
  file_location: "contact.html"
  ignore: ""
