# This workflow builds a list of your starred repositories
name: Site generator

on:
  schedule:
    - cron: '42 2 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # install dependencies
      - name: install dependencies
        run: |
          python -m pip install beautifulsoup4
          python -m pip install ruamel.yaml

      # Generate the webpage
      - name: Cr
        id: stargazer
        run: |
          python generator/gallery.py > gallery.html
          python generator/main.py ${{ secrets.GITHUB_TOKEN }}

      # Commit the changes
      - name: Commit files
        run: |
          git config --local user.email "actions@noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update personnal website"
      # Push the changes
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
